// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	handler "ezproxy/handler"

	mock "github.com/stretchr/testify/mock"
)

// IProxyListener is an autogenerated mock type for the IProxyListener type
type IProxyListener struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, cancel, ca
func (_m *IProxyListener) Execute(ctx context.Context, cancel context.CancelCauseFunc, ca handler.IConnectionAdder) {
	_m.Called(ctx, cancel, ca)
}

// NewIProxyListener creates a new instance of IProxyListener. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProxyListener(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProxyListener {
	mock := &IProxyListener{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
