// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"
	handler "ezproxy/handler"

	mock "github.com/stretchr/testify/mock"
)

// IProxyListner is an autogenerated mock type for the IProxyListner type
type IProxyListner struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, cancel, ca
func (_m *IProxyListner) Execute(ctx context.Context, cancel context.CancelCauseFunc, ca handler.IConnectionAdder) {
	_m.Called(ctx, cancel, ca)
}

// NewIProxyListner creates a new instance of IProxyListner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIProxyListner(t interface {
	mock.TestingT
	Cleanup(func())
}) *IProxyListner {
	mock := &IProxyListner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
