// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	handler "ezproxy/handler"

	mock "github.com/stretchr/testify/mock"
)

// ProxyErrorCallback is an autogenerated mock type for the ProxyErrorCallback type
type ProxyErrorCallback struct {
	mock.Mock
}

// Execute provides a mock function with given fields: err, pc
func (_m *ProxyErrorCallback) Execute(err error, pc handler.IProxyContainer) {
	_m.Called(err, pc)
}

// NewProxyErrorCallback creates a new instance of ProxyErrorCallback. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyErrorCallback(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyErrorCallback {
	mock := &ProxyErrorCallback{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
